title: "Sections"
description: |
  The sections includes various groupings of information found throughout the website.

patterns:
  text-img-section:
    title: "Text and Image Section"
    description: |
      This is a section that include text and image, where the text and image align side by side on large screens. It is used on the about page.
    fields:
      - name: title
        type: string
        example: "Hi! I'm Jess Jodoin."
      - name: parag1
        type: string
        example: "I didn’t think I’d end up here, but boy am I happy I did. Art and all things craft-y have always been a huge part of my life."
      - name: parag2
        type: string
        example: "So, I figured it was easy, right? Just a simple point A to point B. Art makes me happy, so that must be the path for me."
      - name: parag3
        type: string
        example: "Well, I took a little detour (… but the scenic route wasn’t so bad). I went off to UOttawa to study Communications. I really enjoyed it, but I realized after graduating that I this wasn't the career path for me."
      - name: parag4
        type: string
        example: "So, (and this is where is gets good!) I went out on a limb, whipped up a portfolio, and applied to the graphic design program at Algonquin College. And I haven’t looked back since."
      - name: parag5
        type: string
        example: "Finally, I’m where I’m supposed to be (that’s here!). Creating fun and eye-catching designs that help you grow your business, and look good while doing it."
      - name: img
        type: image
        example: "/images/my-photo.jpg"
      - name: alt
        type: string
        example: "A professional photo of myself"
  final-thoughts-section:
    title: "Final Thoughts Section"
    description: |
      This is the final thoughts section found at the bottom of each case study page.
    fields:
      - name: title
        type: string
        example: "Final Thoughts"
      - name: img
        type: image
        example: "/images/adopt-newsletter-mockup-1.jpg"
      - name: img2
        type: image
        example: "/images/adopt-newsletter-mockup-3.jpg"
      - name: alt
        type: string
        example: "This is a mockup image of the adoption newsletter. It is folded to show the cover page.The image has a light background."
      - name: alt2
        type: string
        example: "This is a mockup image of the adoption newsletter. It is laying flat, angled to show in inner spreads. The image has a light background, and page 2 is in focus."
  progress-section:
    title: "Project Progress Section"
    description: |
      This is the project progress section. It contains paragraphs about the project's process and three images of sketches.
    fields:
      - name: title
        type: string
        example: "The Process"
      - name: img
        type: image
        example: "/images/adopt-newsletter-sketches-1.png"
      - name: img2
        type: image
        example: "/images/adopt-newsletter-sketches-2.png"
      - name: img3
        type: image
        example: "/images/adopt-newsletter-sketches-3.png"
      - name: alt
        type: string
        example: "This in an image of my progress sketches for the adoption newsletter. This is the first rough idea for the layout design."
      - name: alt2
        type: string
        example: "This in an image of my progress sketches for the adoption newsletter. This is the second rough idea for the layout design."
      - name: alt3
        type: string
        example: "This in an image of my progress sketches for the adoption newsletter. This is the third and final ideas for the layout design."
  project-text-section:
    title: "Project Text Section"
    description: |
      This is the project text section. It contains information about the project, the deliverables for the project, and my goals for the project.
  side-card-section:
    title: "Side Card Section"
    description: |
      This is a side card section. It is for text — a heading and a paragraph.
  img-overlap-section:
    title: "Image Overlap Section"
    description: |
      This is an image overlap section. It contains two images that overlap each other on an edge.
    fields:
      - name: img1
        type: image
        example: "/images/adopt-newsletter-testprint1.jpg"
      - name: img2
        type: image
        example: "/images/adopt-newsletter-testprint2.jpg"
      - name: alt1
        type: string
        example: "This is an image of a test print during the process of creating the newsletter. It shows the cover page and the back page."
      - name: alt2
        type: string
        example: "This is an image of a test print during the process of creating the newsletter. It shows the inner spreads (page 2 and 3)."
  card-grid-section:
    title: "Card Grid Section"
    description: |
      This is a card grid section. It is used to organize the project cards into a nice grid.
