title: "Sections"
description: |
  The sections includes various groupings of information found throughout the website.

patterns:
  text-img-section:
    title: "Text and Image Section"
    description: |
      This is a section that include text and image, where the text and image align side by side on large screens. It is used on the about page.
    fields:
      - name: title
        type: string
        example: "Hi! I'm Jess Jodoin."
      - name: parag1
        type: string
        example: "I didn’t think I’d end up here, but boy am I happy I did. Art and all things craft-y have always been a huge part of my life."
      - name: parag2
        type: string
        example: "So, I figured it was easy, right? Just a simple point A to point B. Art makes me happy, so that must be the path for me."
      - name: parag3
        type: string
        example: "Well, I took a little detour (… but the scenic route wasn’t so bad). I went off to UOttawa to study Communications. I really enjoyed it, but I realized after graduating that I this wasn't the career path for me."
      - name: parag4
        type: string
        example: "So, (and this is where is gets good!) I went out on a limb, whipped up a portfolio, and applied to the graphic design program at Algonquin College. And I haven’t looked back since."
      - name: parag5
        type: string
        example: "Finally, I’m where I’m supposed to be (that’s here!). Creating fun and eye-catching designs that help you grow your business, and look good while doing it."
      - name: img
        type: image
        example: "/images/my-photo.jpg"
      - name: alt
        type: string
        example: "A professional photo of myself"
  final-thoughts-section:
    title: "Final Thoughts Section"
    description: |
      This is the final thoughts section found at the bottom of each case study page.
    fields:
      - name: title
        type: string
        example: "Final Thoughts"
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
  progress-section:
    title: "Project Progress Section"
    description: |
      This is the project progress section. It contains paragraphs about the project's process and three images of sketches.
    fields:
      - name: title
        type: string
        example: "The Process"
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
  project-text-section:
    title: "Project Text Section"
    description: |
      This is the project text section. It contains information about the project, the deliverables for the project, and my goals for the project.
    fields:
      - name: title1
        type: string
        example: "Project Description"
      - name: title2
        type: string
        example: "Deliverables"
      - name: title3
        type: string
        example: "My Goals"
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
  side-card-section:
    title: "Side Card Section"
    description: |
      This is a side card section. It is for text — a heading and a paragraph.
    fields:
      - name: title
        type: string
        example: "Challenges"
      - name: content
        type: string
        example: "There was a good amount of information that had to fit into the newsletter, trying to give everything the right spacing was a bit challenging."
  side-card-include-section:
    title: "Side Card Section (with data includes)"
    description: |
      This is a side card section. It is for text — a heading and a paragraph. Use with markdown files.
    fields:
      - name: title
        type: string
        example: "Challenges"
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
  img-overlap-section:
    title: "Image Overlap Section"
    description: |
      This is an image overlap section. It contains two images that overlap each other on an edge.
    fields:
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
  work-exp-section:
    title: "Work Experience Section"
    description: |
      This is the work experience section. It contains a heading and a list.
    fields:
      - name: date1
        type: string
        example: "2018 – Current"
      - name: job1
        type: string
        example: "Freelance "
      - name: corp1
        type: string
        example: "Jess Jodoin Design"
      - name: date2
        type: string
        example: "2020"
      - name: job2
        type: string
        example: "Web Dev/Design Teaching Assistant"
      - name: corp2
        type: string
        example: " Algonquin College"
      - name: date3
        type: string
        example: "2019"
      - name: job3
        type: string
        example: "Graphic Design Intern "
      - name: corp3
        type: string
        example: "Solink"
  card-grid-section:
    title: "Card Grid Section"
    description: |
      This is a card grid section. It is used to organize the project cards into a nice grid.
  error-404:
    title: "404 Error Section"
    description: |
      This is the 404 error section. It is used on the 404 page only.
