title: "Cards"
description: |
  Cards should be used to promote each case study is a pleasing way.

patterns:
  project-card:
    title: "Project Card"
    description: |
     This is the card for each project case study, linking to each case study page.
    fields:
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
