title: "Cards"
description: |
  Cards should be used to promote each case study is a more pleasing way.

patterns:
  case-study-card:
    title: "Case Study Card"
    description: |
     This is the card for each case study, linking to each case study page. The hover state is red.
    fields:
      - name: projecttitle
        type: string
        example: "OHS Pet Adoption Newsletter"
      - name: projecttype
        type: string
        example: "Typography"
      - name: img
        type: image
        example: "/images/adopt-newsletter-mockup-2.jpg"
      - name: alt
        type: string
        example: "This is a mockup image of the adoption newsletter. It is laying flat, angled to show in inner spreads. The image has a light background, and page 3 is in focus."
