title: "Cards"
description: |
  Cards should be used to promote each case study is a more pleasing way.

patterns:
  case-study-card:
    title: "Case Study Card"
    description: |
     This is the card for each case study, linking to each case study page. The hover state is red.
    fields:
      - name: data
        type: object
        data:
          source: "site.projects[0]"
          type: project
